export { default as Container } from '@/components/Container.vue'
export { default as Page } from '@/components/Page.vue'
export { default as DataTable } from '@/components/DataTable.vue'
export { default as Tabs } from '@/components/Tabs.vue'
export { default as loading } from '@/plugins/loading'
